FROM golang:1.26-alpine
RUN apk add --no-cache git gcc musl-dev curl postgresql-client docker-cli
RUN go install github.com/air-verse/air@latest
WORKDIR /app
COPY go.mod ./
RUN go mod download || true
CMD ["air", "-c", ".air.toml"]
